### ISSUE TITLE
Can't get newer versions from Jitpack

### ISSUE THREAD

**Issue by Reoseah** [swordglowsblue/artifice#3]
Trying to add latest version by adding to my `build.gradle`:
```gradle
repositories { maven { url "https://jitpack.io" } }
dependencies {
    modCompile "com.github.swordglowsblue:artifice:87196b08fe:dev"
}
```
and I'm getting error
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'OperatingPower'.
> Could not resolve all artifacts for configuration ':modCompile'.
   > Could not download artifice-dev.jar (com.github.swordglowsblue:artifice:87196b08fe)
      > Could not get resource 'https://jitpack.io/com/github/swordglowsblue/artifice/87196b08fe/artifice-87196b08fe-dev.jar'.
         > Could not GET 'https://jitpack.io/com/github/swordglowsblue/artifice/87196b08fe/artifice-87196b08fe-dev.jar'.
            > Read timed out
```
By look of https://jitpack.io/com/github/swordglowsblue/artifice/87196b08fe/build.log it builds, but nothing with `-dev` shows up in resulting files, so Loom cannot use it :/

**Comment by Reoseah** [comment]
Oh, I just had to remove `:dev` from modCompile string. 

So, readme is outdated, it also says to use `modImplementation` that's no longer available..

**Comment by swordglowsblue** [comment]
Yeah, I haven't updated docs to use versions past 0.2.1 since they're not stable yet. 0.3.0 is soon.

**Comment by swordglowsblue** [comment]
Also, the error you got was a Jitpack thing - it takes longer to prepare a version that hasn't been requested yet than Gradle is willing to wait, hence "Read timed out". Nothing directly to do with `:dev`, though I'd leave it removed anyway.

**Comment by Reoseah** [comment]
You can try to open this link in browser and it will always time out: https://jitpack.io/com/github/swordglowsblue/artifice/87196b08fe/artifice-87196b08fe-dev.jar
Remove `-dev` and you'll download file... I got that error after Jitpack build requested version, which is seen in build log.

**Comment by swordglowsblue** [comment]
Still, this is just a case of the documentation not being updated to match an unreleased version. I'll update it when I'm ready to release 0.3.0.
